// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AddTagsToArticleData,
  AddTagsToArticleErrors,
  AddTagsToArticleResponses,
  CountAllPublishedArticlesData,
  CountAllPublishedArticlesResponses,
  CountArticlesByBusinessIdData,
  CountArticlesByBusinessIdErrors,
  CountArticlesByBusinessIdResponses,
  CountArticlesByUserData,
  CountArticlesByUserErrors,
  CountArticlesByUserResponses,
  CreateArticleData,
  CreateArticleErrors,
  CreateArticleResponses,
  CreatePromotionData,
  CreatePromotionErrors,
  CreatePromotionResponses,
  CreateTagData,
  CreateTagErrors,
  CreateTagResponses,
  DeleteArticleByIdData,
  DeleteArticleByIdErrors,
  DeleteArticleByIdResponses,
  DeletePromotionData,
  DeletePromotionErrors,
  DeletePromotionResponses,
  GetActivePromotionsData,
  GetActivePromotionsResponses,
  GetAllArticleCategoriesData,
  GetAllArticleCategoriesResponses,
  GetAllArticlesByBusinessIdData,
  GetAllArticlesByBusinessIdErrors,
  GetAllArticlesByBusinessIdForBusinessUserData,
  GetAllArticlesByBusinessIdForBusinessUserErrors,
  GetAllArticlesByBusinessIdForBusinessUserResponses,
  GetAllArticlesByBusinessIdResponses,
  GetAllArticlesData,
  GetAllArticlesResponses,
  GetAllPromotionsData,
  GetAllPromotionsResponses,
  GetAllTagsByBusinessIdData,
  GetAllTagsByBusinessIdErrors,
  GetAllTagsByBusinessIdResponses,
  GetArticleByIdData,
  GetArticleByIdErrors,
  GetArticleByIdResponses,
  GetArticlesByIdsData,
  GetArticlesByIdsErrors,
  GetArticlesByIdsResponses,
  GetPromotionByIdData,
  GetPromotionByIdErrors,
  GetPromotionByIdResponses,
  GetPromotionsByBusinessIdData,
  GetPromotionsByBusinessIdErrors,
  GetPromotionsByBusinessIdResponses,
  GetPublicPromotionByIdData,
  GetPublicPromotionByIdErrors,
  GetPublicPromotionByIdResponses,
  PublishArticleData,
  PublishArticleErrors,
  PublishArticleResponses,
  UnpublishAllArticlesData,
  UnpublishAllArticlesErrors,
  UnpublishAllArticlesResponses,
  UnpublishArticleData,
  UnpublishArticleErrors,
  UnpublishArticleResponses,
  UpdateArticleByIdData,
  UpdateArticleByIdErrors,
  UpdateArticleByIdResponses,
  UpdatePromotionData,
  UpdatePromotionErrors,
  UpdatePromotionResponses,
  VerifyArticleOwnershipData,
  VerifyArticleOwnershipResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Promotion {
  /**
   * Create a promotion for an article
   *
   * Creates a new promotion for a specific article
   */
  public static createPromotion<ThrowOnError extends boolean = false>(
    options: Options<CreatePromotionData, ThrowOnError>,
  ): RequestResult<
    CreatePromotionResponses,
    CreatePromotionErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      CreatePromotionResponses,
      CreatePromotionErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}/promotion",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete a promotion
   *
   * Deletes a promotion for a specific article
   */
  public static deletePromotion<ThrowOnError extends boolean = false>(
    options: Options<DeletePromotionData, ThrowOnError>,
  ): RequestResult<
    DeletePromotionResponses,
    DeletePromotionErrors,
    ThrowOnError
  > {
    return (options.client ?? client).delete<
      DeletePromotionResponses,
      DeletePromotionErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}/promotion/{promotionId}",
      ...options,
    });
  }

  /**
   * Update a promotion
   *
   * Updates an existing promotion for a specific article
   */
  public static updatePromotion<ThrowOnError extends boolean = false>(
    options: Options<UpdatePromotionData, ThrowOnError>,
  ): RequestResult<
    UpdatePromotionResponses,
    UpdatePromotionErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UpdatePromotionResponses,
      UpdatePromotionErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}/promotion/{promotionId}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get all promotions
   *
   * Retrieves a paginated list of promotions with optional filters
   */
  public static getAllPromotions<ThrowOnError extends boolean = false>(
    options: Options<GetAllPromotionsData, ThrowOnError>,
  ): RequestResult<GetAllPromotionsResponses, unknown, ThrowOnError> {
    return (options.client ?? client).get<
      GetAllPromotionsResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/promotion", ...options });
  }

  /**
   * Get all active promotions
   *
   * Retrieves a paginated list of currently active promotions across all businesses
   */
  public static getActivePromotions<ThrowOnError extends boolean = false>(
    options: Options<GetActivePromotionsData, ThrowOnError>,
  ): RequestResult<GetActivePromotionsResponses, unknown, ThrowOnError> {
    return (options.client ?? client).get<
      GetActivePromotionsResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/promotion/active", ...options });
  }

  /**
   * Get a promotion by ID (public)
   *
   * Retrieves a specific promotion by its ID without authentication
   */
  public static getPublicPromotionById<ThrowOnError extends boolean = false>(
    options: Options<GetPublicPromotionByIdData, ThrowOnError>,
  ): RequestResult<
    GetPublicPromotionByIdResponses,
    GetPublicPromotionByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetPublicPromotionByIdResponses,
      GetPublicPromotionByIdErrors,
      ThrowOnError
    >({ url: "/public/promotion/{promotionId}", ...options });
  }

  /**
   * Get all promotions of a business
   *
   * Retrieves a paginated list of promotions for a specific business
   */
  public static getPromotionsByBusinessId<ThrowOnError extends boolean = false>(
    options: Options<GetPromotionsByBusinessIdData, ThrowOnError>,
  ): RequestResult<
    GetPromotionsByBusinessIdResponses,
    GetPromotionsByBusinessIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetPromotionsByBusinessIdResponses,
      GetPromotionsByBusinessIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/promotion",
      ...options,
    });
  }

  /**
   * Get a promotion by ID
   *
   * Retrieves a specific promotion by its ID for business collaborators
   */
  public static getPromotionById<ThrowOnError extends boolean = false>(
    options: Options<GetPromotionByIdData, ThrowOnError>,
  ): RequestResult<
    GetPromotionByIdResponses,
    GetPromotionByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetPromotionByIdResponses,
      GetPromotionByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/promotion/{promotionId}",
      ...options,
    });
  }
}

export class Article {
  /**
   * Get all articles of a business (private)
   *
   * Retrieves a paginated list of articles for a business (all statuses) with optional filters.
   */
  public static getAllArticlesByBusinessIdForBusinessUser<
    ThrowOnError extends boolean = false,
  >(
    options: Options<
      GetAllArticlesByBusinessIdForBusinessUserData,
      ThrowOnError
    >,
  ): RequestResult<
    GetAllArticlesByBusinessIdForBusinessUserResponses,
    GetAllArticlesByBusinessIdForBusinessUserErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetAllArticlesByBusinessIdForBusinessUserResponses,
      GetAllArticlesByBusinessIdForBusinessUserErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article",
      ...options,
    });
  }

  /**
   * Create a new article
   *
   * Creates a new article and returns its ID.
   */
  public static createArticle<ThrowOnError extends boolean = false>(
    options: Options<CreateArticleData, ThrowOnError>,
  ): RequestResult<CreateArticleResponses, CreateArticleErrors, ThrowOnError> {
    return (options.client ?? client).post<
      CreateArticleResponses,
      CreateArticleErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get all articles of a business
   *
   * Retrieves a paginated list of published articles with optional filters.
   */
  public static getAllArticlesByBusinessId<
    ThrowOnError extends boolean = false,
  >(
    options: Options<GetAllArticlesByBusinessIdData, ThrowOnError>,
  ): RequestResult<
    GetAllArticlesByBusinessIdResponses,
    GetAllArticlesByBusinessIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetAllArticlesByBusinessIdResponses,
      GetAllArticlesByBusinessIdErrors,
      ThrowOnError
    >({ url: "/public/business/{businessId}/article", ...options });
  }

  /**
   * Get all article categories
   *
   * Retrieves all available article categories.
   */
  public static getAllArticleCategories<ThrowOnError extends boolean = false>(
    options?: Options<GetAllArticleCategoriesData, ThrowOnError>,
  ): RequestResult<GetAllArticleCategoriesResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      GetAllArticleCategoriesResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/article/category", ...options });
  }

  /**
   * Get article by ID
   *
   * Retrieves an article by its ID.
   */
  public static getArticleById<ThrowOnError extends boolean = false>(
    options: Options<GetArticleByIdData, ThrowOnError>,
  ): RequestResult<
    GetArticleByIdResponses,
    GetArticleByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetArticleByIdResponses,
      GetArticleByIdErrors,
      ThrowOnError
    >({ url: "/public/business/{businessId}/article/{articleId}", ...options });
  }

  /**
   * Delete article by ID
   *
   * Deletes an article by its ID.
   */
  public static deleteArticleById<ThrowOnError extends boolean = false>(
    options: Options<DeleteArticleByIdData, ThrowOnError>,
  ): RequestResult<
    DeleteArticleByIdResponses,
    DeleteArticleByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).delete<
      DeleteArticleByIdResponses,
      DeleteArticleByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}",
      ...options,
    });
  }

  /**
   * Update article by ID
   *
   * Updates an existing article by its ID.
   */
  public static updateArticleById<ThrowOnError extends boolean = false>(
    options: Options<UpdateArticleByIdData, ThrowOnError>,
  ): RequestResult<
    UpdateArticleByIdResponses,
    UpdateArticleByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UpdateArticleByIdResponses,
      UpdateArticleByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Verify that articles belong to the business
   *
   * Returns whether all provided article IDs belong to the specified business.
   */
  public static verifyArticleOwnership<ThrowOnError extends boolean = false>(
    options: Options<VerifyArticleOwnershipData, ThrowOnError>,
  ): RequestResult<VerifyArticleOwnershipResponses, unknown, ThrowOnError> {
    return (options.client ?? client).post<
      VerifyArticleOwnershipResponses,
      unknown,
      ThrowOnError
    >({
      url: "/public/business/{businessId}/article/verify-ownership",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get articles by IDs
   *
   * Returns articles that match the provided IDs.
   */
  public static getArticlesByIds<ThrowOnError extends boolean = false>(
    options: Options<GetArticlesByIdsData, ThrowOnError>,
  ): RequestResult<
    GetArticlesByIdsResponses,
    GetArticlesByIdsErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      GetArticlesByIdsResponses,
      GetArticlesByIdsErrors,
      ThrowOnError
    >({
      url: "/public/article/by-ids",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Count articles by business ID
   *
   * Retrieves the total number of articles for a given business, optionally filtered by status.
   */
  public static countArticlesByBusinessId<ThrowOnError extends boolean = false>(
    options: Options<CountArticlesByBusinessIdData, ThrowOnError>,
  ): RequestResult<
    CountArticlesByBusinessIdResponses,
    CountArticlesByBusinessIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      CountArticlesByBusinessIdResponses,
      CountArticlesByBusinessIdErrors,
      ThrowOnError
    >({ url: "/public/business/{businessId}/article/count", ...options });
  }

  /**
   * Count all published articles
   *
   * Retrieves the total number of published articles across all businesses.
   */
  public static countAllPublishedArticles<ThrowOnError extends boolean = false>(
    options?: Options<CountAllPublishedArticlesData, ThrowOnError>,
  ): RequestResult<CountAllPublishedArticlesResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      CountAllPublishedArticlesResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/article/count", ...options });
  }

  /**
   * Count articles created by users per business
   *
   * Returns the number of articles created by each specified user for each specified business.
   */
  public static countArticlesByUser<ThrowOnError extends boolean = false>(
    options: Options<CountArticlesByUserData, ThrowOnError>,
  ): RequestResult<
    CountArticlesByUserResponses,
    CountArticlesByUserErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      CountArticlesByUserResponses,
      CountArticlesByUserErrors,
      ThrowOnError
    >({
      url: "/public/article/count-by-user",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Publish article
   *
   * Publishes an article by its ID.
   */
  public static publishArticle<ThrowOnError extends boolean = false>(
    options: Options<PublishArticleData, ThrowOnError>,
  ): RequestResult<
    PublishArticleResponses,
    PublishArticleErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      PublishArticleResponses,
      PublishArticleErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}/publish",
      ...options,
    });
  }

  /**
   * Unpublish article
   *
   * Removes an article from publication.
   */
  public static unpublishArticle<ThrowOnError extends boolean = false>(
    options: Options<UnpublishArticleData, ThrowOnError>,
  ): RequestResult<
    UnpublishArticleResponses,
    UnpublishArticleErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UnpublishArticleResponses,
      UnpublishArticleErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}/unpublish",
      ...options,
    });
  }

  /**
   * Unpublish all articles for a business
   *
   * Unpublishes all published articles belonging to the specified business.
   */
  public static unpublishAllArticles<ThrowOnError extends boolean = false>(
    options: Options<UnpublishAllArticlesData, ThrowOnError>,
  ): RequestResult<
    UnpublishAllArticlesResponses,
    UnpublishAllArticlesErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UnpublishAllArticlesResponses,
      UnpublishAllArticlesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/unpublish-all",
      ...options,
    });
  }

  /**
   * Get all articles
   *
   * Retrieves a paginated list of articles with optional filters.
   */
  public static getAllArticles<ThrowOnError extends boolean = false>(
    options: Options<GetAllArticlesData, ThrowOnError>,
  ): RequestResult<GetAllArticlesResponses, unknown, ThrowOnError> {
    return (options.client ?? client).get<
      GetAllArticlesResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/article", ...options });
  }
}

export class Tag {
  /**
   * Create a new tag
   *
   * Creates a new tag for a business and returns its ID.
   */
  public static createTag<ThrowOnError extends boolean = false>(
    options: Options<CreateTagData, ThrowOnError>,
  ): RequestResult<CreateTagResponses, CreateTagErrors, ThrowOnError> {
    return (options.client ?? client).post<
      CreateTagResponses,
      CreateTagErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/tag",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Add tags to an article
   *
   * Adds one or more existing tags to an article. Tags already linked to the article are ignored.
   */
  public static addTagsToArticle<ThrowOnError extends boolean = false>(
    options: Options<AddTagsToArticleData, ThrowOnError>,
  ): RequestResult<
    AddTagsToArticleResponses,
    AddTagsToArticleErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      AddTagsToArticleResponses,
      AddTagsToArticleErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/article/{articleId}/tag",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get all tags by business ID
   *
   * Retrieves a paginated list of tags for a business with optional search filters (title, description).
   */
  public static getAllTagsByBusinessId<ThrowOnError extends boolean = false>(
    options: Options<GetAllTagsByBusinessIdData, ThrowOnError>,
  ): RequestResult<
    GetAllTagsByBusinessIdResponses,
    GetAllTagsByBusinessIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetAllTagsByBusinessIdResponses,
      GetAllTagsByBusinessIdErrors,
      ThrowOnError
    >({ url: "/public/business/{businessId}/tags", ...options });
  }
}
