// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8181/api" | (string & {});
};

export type ArticleCategoryDto = {
  /**
   * Unique identifier of the business type
   */
  id?: string;
  /**
   * English name of the business type
   */
  nameEn?: string;
  /**
   * English description of the business type
   */
  descriptionEn?: string;
  /**
   * French name of the business type
   */
  nameFr?: string;
  /**
   * French description of the business type
   */
  descriptionFr?: string;
};

export type PromotionIdDto = {
  id: string;
};

export const PromotionSortFieldDto = {
  CREATED_AT: "CREATED_AT",
  START_DATE: "START_DATE",
  END_DATE: "END_DATE",
  DISCOUNT_PERCENTAGE: "DISCOUNT_PERCENTAGE",
  STATUS: "STATUS",
} as const;

export type PromotionSortFieldDto =
  (typeof PromotionSortFieldDto)[keyof typeof PromotionSortFieldDto];

export const PromotionStatusDto = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  SCHEDULED: "SCHEDULED",
} as const;

export type PromotionStatusDto =
  (typeof PromotionStatusDto)[keyof typeof PromotionStatusDto];

export type CreatePromotionDto = {
  discountPercentage: number;
  startDate: string;
  endDate: string;
  description?: string;
};

export type UpdatePromotionDto = {
  discountPercentage?: number;
  startDate?: string;
  endDate?: string;
  description?: string;
};

export type PromotionDto = {
  id: string;
  article?: ArticleDto;
  businessId: string;
  discountPercentage: number;
  startDate: string;
  endDate: string;
  description?: string;
  status: PromotionStatusDto;
  createdAt?: string;
  originalPrice?: MoneyDto;
  productName?: string;
  productDescription?: string;
  productImages?: {
    [key: string]: string;
  };
  productCategory?: ArticleCategoryDto;
  productQuantity?: number;
  productSpecifications?: {
    [key: string]: string;
  };
};

export type PromotionPageableResponseDto = {
  content?: Array<PromotionDto>;
  page?: PageableResponsePageDto;
};

export type CountResponseDto = {
  value: number;
};

export const ArticleSortFieldDto = {
  CREATED_AT: "CREATED_AT",
  NAME: "NAME",
  PRICE: "PRICE",
} as const;

export type ArticleSortFieldDto =
  (typeof ArticleSortFieldDto)[keyof typeof ArticleSortFieldDto];

export const SortDirectionDto = { ASC: "ASC", DESC: "DESC" } as const;

export type SortDirectionDto =
  (typeof SortDirectionDto)[keyof typeof SortDirectionDto];

export type ArticlePageableResponseDto = {
  content?: Array<ArticleDto>;
  page?: PageableResponsePageDto;
};

export type TagPageableResponseDto = {
  content?: Array<TagDto>;
  page?: PageableResponsePageDto;
};

export type PageableResponsePageDto = {
  /**
   * Number of items per page
   */
  size?: number;
  /**
   * Current page number (zero-based)
   */
  number?: number;
  /**
   * Total number of items across all pages
   */
  totalElements?: number;
  /**
   * Total number of pages
   */
  totalPages?: number;
};

export type VerifyOwnershipRequestDto = {
  productIds: Array<string>;
};

export type ArticleIdsRequestDto = {
  productIds: Array<string>;
};

export type CountByUserRequestDto = {
  queries: Array<CountByUserQueryDto>;
};

export type CountByUserQueryDto = {
  /**
   * Username of the article creator
   */
  username: string;
  /**
   * Business identifier
   */
  businessId: string;
};

export type CountByUserResponseDto = {
  results: Array<CountByUserResultDto>;
};

export type CountByUserResultDto = {
  /**
   * Username of the article creator
   */
  username: string;
  /**
   * Business identifier
   */
  businessId: string;
  /**
   * Number of articles created by this user for this business
   */
  count: number;
};

export type VerifyOwnershipResponseDto = {
  /**
   * True if all provided productIds belong to the business
   */
  valid: boolean;
};

export type MoneyDto = {
  amount: number;
  currency: string;
};

export type ArticleIdDto = {
  id: string;
};

export type AddTagsToArticleDto = {
  /**
   * List of tag identifiers to link to the article. Tags already attached are ignored.
   */
  tagIds: Array<string>;
};

export type TagIdDto = {
  id: string;
};

export type CreateTagDto = {
  /**
   * Title of the tag
   */
  title: string;
  /**
   * Description of the tag
   */
  description?: string;
};

export type TagDto = {
  id: string;
  /**
   * Title of the tag
   */
  title: string;
  /**
   * Description of the tag
   */
  description?: string;
  /**
   * Business identifier
   */
  businessId: string;
  createdAt?: string;
  updatedAt?: string;
};

export const ArticleStatusDto = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  UNPUBLISHED: "UNPUBLISHED",
} as const;

export type ArticleStatusDto =
  (typeof ArticleStatusDto)[keyof typeof ArticleStatusDto];

export type ArticleDto = {
  id: string;
  name: string;
  description: string;
  category: ArticleCategoryDto;
  price: MoneyDto;
  quantity: number;
  /**
   * Product specifications as key-value pairs (e.g. size: XXL)
   */
  specifications: {
    [key: string]: string;
  };
  images?: {
    [key: string]: string;
  };
  createdAt: string;
  updatedAt: string;
  businessId: string;
  createdBy: string;
  status?: ArticleStatusDto;
  tags?: Array<TagDto>;
};

export type CreateArticleDto = {
  name: string;
  description?: string;
  category: string;
  price: MoneyDto;
  quantity: number;
  /**
   * Product specifications as key-value pairs (e.g. size: XXL)
   */
  specifications: {
    [key: string]: string;
  };
  images?: {
    [key: string]: string;
  };
  /**
   * Optional list of tag IDs to associate with the article
   */
  tagIds?: Array<string>;
};

export type UpdateArticleDto = {
  name?: string;
  description?: string;
  categoryId?: string;
  price?: MoneyDto;
  quantity?: number;
  /**
   * Product specifications as key-value pairs (e.g. size: XXL)
   */
  specifications?: {
    [key: string]: string;
  } | null;
  images?: {
    [key: string]: string;
  } | null;
  /**
   * Optional list of tag IDs to update/overwrite for the article
   */
  tagIds?: Array<string>;
};

export type CreatePromotionData = {
  body: CreatePromotionDto;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}/promotion";
};

export type CreatePromotionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Article not found
   */
  404: unknown;
};

export type CreatePromotionResponses = {
  /**
   * Promotion created successfully
   */
  201: PromotionIdDto;
};

export type CreatePromotionResponse =
  CreatePromotionResponses[keyof CreatePromotionResponses];

export type DeletePromotionData = {
  body?: never;
  path: {
    businessId: string;
    articleId: string;
    promotionId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}/promotion/{promotionId}";
};

export type DeletePromotionErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Promotion not found
   */
  404: unknown;
};

export type DeletePromotionResponses = {
  /**
   * Promotion deleted successfully
   */
  204: void;
};

export type DeletePromotionResponse =
  DeletePromotionResponses[keyof DeletePromotionResponses];

export type UpdatePromotionData = {
  body: UpdatePromotionDto;
  path: {
    businessId: string;
    articleId: string;
    promotionId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}/promotion/{promotionId}";
};

export type UpdatePromotionErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Promotion not found
   */
  404: unknown;
};

export type UpdatePromotionResponses = {
  /**
   * Promotion updated successfully
   */
  204: void;
};

export type UpdatePromotionResponse =
  UpdatePromotionResponses[keyof UpdatePromotionResponses];

export type GetAllPromotionsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: PromotionSortFieldDto;
    direction?: SortDirectionDto;
    status?: PromotionStatusDto;
    /**
     * Filter by business ID
     */
    businessId?: string;
    /**
     * Filter by promotion name (case-insensitive)
     */
    name?: string;
  };
  url: "/public/promotion";
};

export type GetAllPromotionsResponses = {
  /**
   * Paginated list of promotions
   */
  200: PromotionPageableResponseDto;
};

export type GetAllPromotionsResponse =
  GetAllPromotionsResponses[keyof GetAllPromotionsResponses];

export type GetActivePromotionsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: PromotionSortFieldDto;
    direction?: SortDirectionDto;
    /**
     * Filter by promotion name (case-insensitive)
     */
    name?: string;
  };
  url: "/public/promotion/active";
};

export type GetActivePromotionsResponses = {
  /**
   * Paginated list of active promotions
   */
  200: PromotionPageableResponseDto;
};

export type GetActivePromotionsResponse =
  GetActivePromotionsResponses[keyof GetActivePromotionsResponses];

export type GetPublicPromotionByIdData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the promotion
     */
    promotionId: string;
  };
  query?: never;
  url: "/public/promotion/{promotionId}";
};

export type GetPublicPromotionByIdErrors = {
  /**
   * Promotion not found
   */
  404: unknown;
};

export type GetPublicPromotionByIdResponses = {
  /**
   * Promotion found
   */
  200: PromotionDto;
};

export type GetPublicPromotionByIdResponse =
  GetPublicPromotionByIdResponses[keyof GetPublicPromotionByIdResponses];

export type GetPromotionsByBusinessIdData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the business
     */
    businessId: string;
  };
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: PromotionSortFieldDto;
    direction?: SortDirectionDto;
    status?: PromotionStatusDto;
  };
  url: "/business/{businessId}/promotion";
};

export type GetPromotionsByBusinessIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetPromotionsByBusinessIdResponses = {
  /**
   * Paginated list of promotions
   */
  200: PromotionPageableResponseDto;
};

export type GetPromotionsByBusinessIdResponse =
  GetPromotionsByBusinessIdResponses[keyof GetPromotionsByBusinessIdResponses];

export type GetPromotionByIdData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the business
     */
    businessId: string;
    /**
     * The unique identifier of the promotion
     */
    promotionId: string;
  };
  query?: never;
  url: "/business/{businessId}/promotion/{promotionId}";
};

export type GetPromotionByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Promotion not found
   */
  404: unknown;
};

export type GetPromotionByIdResponses = {
  /**
   * Promotion found
   */
  200: PromotionDto;
};

export type GetPromotionByIdResponse =
  GetPromotionByIdResponses[keyof GetPromotionByIdResponses];

export type GetAllArticlesByBusinessIdForBusinessUserData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the business
     */
    businessId: string;
  };
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: ArticleSortFieldDto;
    direction?: SortDirectionDto;
    status?: ArticleStatusDto;
    category?: string;
    /**
     * Filter by article name (case-insensitive)
     */
    name?: string;
    /**
     * Filter by tag IDs
     */
    tags?: Array<string>;
  };
  url: "/business/{businessId}/article";
};

export type GetAllArticlesByBusinessIdForBusinessUserErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type GetAllArticlesByBusinessIdForBusinessUserResponses = {
  /**
   * Paginated list of articles
   */
  200: ArticlePageableResponseDto;
};

export type GetAllArticlesByBusinessIdForBusinessUserResponse =
  GetAllArticlesByBusinessIdForBusinessUserResponses[keyof GetAllArticlesByBusinessIdForBusinessUserResponses];

export type CreateArticleData = {
  body: CreateArticleDto;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/business/{businessId}/article";
};

export type CreateArticleErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
};

export type CreateArticleResponses = {
  /**
   * Article created successfully
   */
  201: ArticleIdDto;
};

export type CreateArticleResponse =
  CreateArticleResponses[keyof CreateArticleResponses];

export type CreateTagData = {
  body: CreateTagDto;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/business/{businessId}/tag";
};

export type CreateTagErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Tag with this title already exists for this business
   */
  409: unknown;
};

export type CreateTagResponses = {
  /**
   * Tag created successfully
   */
  201: TagIdDto;
};

export type CreateTagResponse = CreateTagResponses[keyof CreateTagResponses];

export type AddTagsToArticleData = {
  body: AddTagsToArticleDto;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}/tag";
};

export type AddTagsToArticleErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Article or tag not found
   */
  404: unknown;
};

export type AddTagsToArticleResponses = {
  /**
   * Tags added to article successfully
   */
  204: void;
};

export type AddTagsToArticleResponse =
  AddTagsToArticleResponses[keyof AddTagsToArticleResponses];

export type GetAllTagsByBusinessIdData = {
  body?: never;
  path: {
    /**
     * Business ID
     */
    businessId: string;
  };
  query?: {
    /**
     * Page number (zero-based)
     */
    page?: number;
    /**
     * Number of items per page
     */
    size?: number;
    /**
     * Sort direction (ASC, DESC) by creation date
     */
    direction?: SortDirectionDto;
    /**
     * Search query string to filter in tag title or description
     */
    query?: string;
  };
  url: "/public/business/{businessId}/tags";
};

export type GetAllTagsByBusinessIdErrors = {
  /**
   * Business not found
   */
  404: unknown;
};

export type GetAllTagsByBusinessIdResponses = {
  /**
   * Tags retrieved successfully
   */
  200: TagPageableResponseDto;
};

export type GetAllTagsByBusinessIdResponse =
  GetAllTagsByBusinessIdResponses[keyof GetAllTagsByBusinessIdResponses];

export type GetAllArticlesByBusinessIdData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the business
     */
    businessId: string;
  };
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: ArticleSortFieldDto;
    direction?: SortDirectionDto;
    category?: string;
    /**
     * Filter by tag IDs
     */
    tags?: Array<string>;
  };
  url: "/public/business/{businessId}/article";
};

export type GetAllArticlesByBusinessIdErrors = {
  /**
   * Business not found
   */
  404: unknown;
};

export type GetAllArticlesByBusinessIdResponses = {
  /**
   * Paginated list of articles
   */
  200: ArticlePageableResponseDto;
};

export type GetAllArticlesByBusinessIdResponse =
  GetAllArticlesByBusinessIdResponses[keyof GetAllArticlesByBusinessIdResponses];

export type GetAllArticleCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/article/category";
};

export type GetAllArticleCategoriesResponses = {
  /**
   * List of article categories
   */
  200: Array<ArticleCategoryDto>;
};

export type GetAllArticleCategoriesResponse =
  GetAllArticleCategoriesResponses[keyof GetAllArticleCategoriesResponses];

export type GetArticleByIdData = {
  body?: never;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/public/business/{businessId}/article/{articleId}";
};

export type GetArticleByIdErrors = {
  /**
   * Article not found
   */
  404: unknown;
};

export type GetArticleByIdResponses = {
  /**
   * Article found
   */
  200: ArticleDto;
};

export type GetArticleByIdResponse =
  GetArticleByIdResponses[keyof GetArticleByIdResponses];

export type DeleteArticleByIdData = {
  body?: never;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}";
};

export type DeleteArticleByIdErrors = {
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Article not found
   */
  404: unknown;
};

export type DeleteArticleByIdResponses = {
  /**
   * Article deleted successfully
   */
  204: void;
};

export type DeleteArticleByIdResponse =
  DeleteArticleByIdResponses[keyof DeleteArticleByIdResponses];

export type UpdateArticleByIdData = {
  body: UpdateArticleDto;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}";
};

export type UpdateArticleByIdErrors = {
  /**
   * Invalid input
   */
  400: unknown;
  /**
   * Unauthorized
   */
  401: unknown;
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Article not found
   */
  404: unknown;
};

export type UpdateArticleByIdResponses = {
  /**
   * Article updated successfully
   */
  204: void;
};

export type UpdateArticleByIdResponse =
  UpdateArticleByIdResponses[keyof UpdateArticleByIdResponses];

export type VerifyArticleOwnershipData = {
  body: VerifyOwnershipRequestDto;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/public/business/{businessId}/article/verify-ownership";
};

export type VerifyArticleOwnershipResponses = {
  /**
   * Ownership verification result
   */
  200: VerifyOwnershipResponseDto;
};

export type VerifyArticleOwnershipResponse =
  VerifyArticleOwnershipResponses[keyof VerifyArticleOwnershipResponses];

export type GetArticlesByIdsData = {
  body: ArticleIdsRequestDto;
  path?: never;
  query?: {
    /**
     * Specifies which product fields should be extracted and returned in the response.
     */
    extractCode?: string;
  };
  url: "/public/article/by-ids";
};

export type GetArticlesByIdsErrors = {
  /**
   * Invalid request
   */
  400: unknown;
};

export type GetArticlesByIdsResponses = {
  /**
   * Articles list
   */
  200: Array<ArticleDto>;
};

export type GetArticlesByIdsResponse =
  GetArticlesByIdsResponses[keyof GetArticlesByIdsResponses];

export type CountArticlesByBusinessIdData = {
  body?: never;
  path: {
    businessId: string;
  };
  query?: {
    /**
     * Filter by article status. If not provided, counts all articles regardless of status.
     */
    status?: ArticleStatusDto;
  };
  url: "/public/business/{businessId}/article/count";
};

export type CountArticlesByBusinessIdErrors = {
  /**
   * Invalid status value
   */
  400: unknown;
  /**
   * Business not found
   */
  404: unknown;
};

export type CountArticlesByBusinessIdResponses = {
  /**
   * Total number of articles
   */
  200: CountResponseDto;
};

export type CountArticlesByBusinessIdResponse =
  CountArticlesByBusinessIdResponses[keyof CountArticlesByBusinessIdResponses];

export type CountAllPublishedArticlesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/article/count";
};

export type CountAllPublishedArticlesResponses = {
  /**
   * Total number of published articles
   */
  200: CountResponseDto;
};

export type CountAllPublishedArticlesResponse =
  CountAllPublishedArticlesResponses[keyof CountAllPublishedArticlesResponses];

export type CountArticlesByUserData = {
  body: CountByUserRequestDto;
  path?: never;
  query?: never;
  url: "/public/article/count-by-user";
};

export type CountArticlesByUserErrors = {
  /**
   * Invalid request
   */
  400: unknown;
};

export type CountArticlesByUserResponses = {
  /**
   * Article counts per user and business
   */
  200: CountByUserResponseDto;
};

export type CountArticlesByUserResponse =
  CountArticlesByUserResponses[keyof CountArticlesByUserResponses];

export type PublishArticleData = {
  body?: never;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}/publish";
};

export type PublishArticleErrors = {
  /**
   * Not authorized to publish this article
   */
  403: unknown;
  /**
   * Article not found
   */
  404: unknown;
};

export type PublishArticleResponses = {
  /**
   * Article successfully published
   */
  204: void;
};

export type PublishArticleResponse =
  PublishArticleResponses[keyof PublishArticleResponses];

export type UnpublishArticleData = {
  body?: never;
  path: {
    businessId: string;
    articleId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/{articleId}/unpublish";
};

export type UnpublishArticleErrors = {
  /**
   * Not authorized to unpublish this article
   */
  403: unknown;
  /**
   * Article not found
   */
  404: unknown;
};

export type UnpublishArticleResponses = {
  /**
   * Article successfully unpublished
   */
  204: void;
};

export type UnpublishArticleResponse =
  UnpublishArticleResponses[keyof UnpublishArticleResponses];

export type UnpublishAllArticlesData = {
  body?: never;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/business/{businessId}/article/unpublish-all";
};

export type UnpublishAllArticlesErrors = {
  /**
   * Forbidden
   */
  403: unknown;
  /**
   * Business not found
   */
  404: unknown;
};

export type UnpublishAllArticlesResponses = {
  /**
   * All articles unpublished successfully
   */
  204: void;
};

export type UnpublishAllArticlesResponse =
  UnpublishAllArticlesResponses[keyof UnpublishAllArticlesResponses];

export type GetAllArticlesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: ArticleSortFieldDto;
    direction?: SortDirectionDto;
    category?: string;
    /**
     * Filter by article name (case-insensitive)
     */
    name?: string;
    /**
     * Filter by tag IDs
     */
    tags?: Array<string>;
  };
  url: "/public/article";
};

export type GetAllArticlesResponses = {
  /**
   * Paginated list of articles
   */
  200: ArticlePageableResponseDto;
};

export type GetAllArticlesResponse =
  GetAllArticlesResponses[keyof GetAllArticlesResponses];
