// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  AcceptInvitationData,
  AcceptInvitationErrors,
  AcceptInvitationResponses,
  CancelInvitationData,
  CancelInvitationErrors,
  CancelInvitationResponses,
  CountCollaboratorsByBusinessIdData,
  CountCollaboratorsByBusinessIdResponses,
  CreateMyBusinessData,
  CreateMyBusinessErrors,
  CreateMyBusinessResponses,
  DeleteBusinessByIdData,
  DeleteBusinessByIdErrors,
  DeleteBusinessByIdResponses,
  DeleteBusinessZoneByIdData,
  DeleteBusinessZoneByIdErrors,
  DeleteBusinessZoneByIdResponses,
  GetAllBusinessesData,
  GetAllBusinessesResponses,
  GetAllBusinessesZoneData,
  GetAllBusinessesZoneResponses,
  GetAllBusinessTypesData,
  GetAllBusinessTypesResponses,
  GetBusinessByIdData,
  GetBusinessByIdErrors,
  GetBusinessByIdResponses,
  GetBusinessCollaboratorsData,
  GetBusinessCollaboratorsResponses,
  GetBusinessesByIdsData,
  GetBusinessesByIdsResponses,
  GetBusinessInvitationsData,
  GetBusinessInvitationsResponses,
  GetMyBusinessCountData,
  GetMyBusinessCountErrors,
  GetMyBusinessCountResponses,
  GetMyBusinessesData,
  GetMyBusinessesResponses,
  GetMyBusinessZoneData,
  GetMyBusinessZoneResponses,
  GetMyCollaborationsData,
  GetMyCollaborationsErrors,
  GetMyCollaborationsResponses,
  GetMyInvitationsData,
  GetMyInvitationsResponses,
  GetUserPermissionsData,
  GetUserPermissionsErrors,
  GetUserPermissionsResponses,
  PublishMyBusinessData,
  PublishMyBusinessErrors,
  PublishMyBusinessResponses,
  RejectInvitationData,
  RejectInvitationErrors,
  RejectInvitationResponses,
  RemoveCollaboratorFromBusinessData,
  RemoveCollaboratorFromBusinessResponses,
  SendCollaborationInvitationData,
  SendCollaborationInvitationErrors,
  SendCollaborationInvitationResponses,
  UnpublishMyBusinessData,
  UnpublishMyBusinessErrors,
  UnpublishMyBusinessResponses,
  UpdateBusinessImagesData,
  UpdateBusinessImagesErrors,
  UpdateBusinessImagesResponses,
  UpdateMyBusinessesData,
  UpdateMyBusinessesErrors,
  UpdateMyBusinessesResponses,
  UpdateMyBusinessZoneData,
  UpdateMyBusinessZoneErrors,
  UpdateMyBusinessZoneResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Invitation {
  /**
   * Get all my invitations
   *
   * Retrieves a list of all pending invitations for the authenticated user.
   */
  public static getMyInvitations<ThrowOnError extends boolean = false>(
    options?: Options<GetMyInvitationsData, ThrowOnError>,
  ): RequestResult<GetMyInvitationsResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      GetMyInvitationsResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/invitations",
      ...options,
    });
  }

  /**
   * Accept an invitation
   *
   * Accepts a pending invitation to join a business as a collaborator.
   */
  public static acceptInvitation<ThrowOnError extends boolean = false>(
    options: Options<AcceptInvitationData, ThrowOnError>,
  ): RequestResult<
    AcceptInvitationResponses,
    AcceptInvitationErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      AcceptInvitationResponses,
      AcceptInvitationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/invitations/{invitationId}/accept",
      ...options,
    });
  }

  /**
   * Reject an invitation
   *
   * Rejects a pending invitation to join a business.
   */
  public static rejectInvitation<ThrowOnError extends boolean = false>(
    options: Options<RejectInvitationData, ThrowOnError>,
  ): RequestResult<
    RejectInvitationResponses,
    RejectInvitationErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      RejectInvitationResponses,
      RejectInvitationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/invitations/{invitationId}/reject",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get invitations for a business
   *
   * Retrieves a list of invitations sent for a specific business. Only accessible by the owner.
   */
  public static getBusinessInvitations<ThrowOnError extends boolean = false>(
    options: Options<GetBusinessInvitationsData, ThrowOnError>,
  ): RequestResult<GetBusinessInvitationsResponses, unknown, ThrowOnError> {
    return (options.client ?? client).get<
      GetBusinessInvitationsResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/invitations",
      ...options,
    });
  }

  /**
   * Cancel a pending invitation
   *
   * Cancels a pending invitation. Only the owner of the business can cancel invitations.
   */
  public static cancelInvitation<ThrowOnError extends boolean = false>(
    options: Options<CancelInvitationData, ThrowOnError>,
  ): RequestResult<
    CancelInvitationResponses,
    CancelInvitationErrors,
    ThrowOnError
  > {
    return (options.client ?? client).delete<
      CancelInvitationResponses,
      CancelInvitationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/invitations/{invitationId}/cancel",
      ...options,
    });
  }
}

export class Business {
  /**
   * Get all collaborators
   *
   * Retrieves a list of all collaborators for a specific business.
   */
  public static getBusinessCollaborators<ThrowOnError extends boolean = false>(
    options: Options<GetBusinessCollaboratorsData, ThrowOnError>,
  ): RequestResult<GetBusinessCollaboratorsResponses, unknown, ThrowOnError> {
    return (options.client ?? client).get<
      GetBusinessCollaboratorsResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/collaborator",
      ...options,
    });
  }

  /**
   * Send a collaboration invitation to an existing user
   *
   * Sends an invitation to an existing user to join the specified business as a collaborator. The invitation must be accepted by the invitee before they become an active collaborator.
   */
  public static sendCollaborationInvitation<
    ThrowOnError extends boolean = false,
  >(
    options: Options<SendCollaborationInvitationData, ThrowOnError>,
  ): RequestResult<
    SendCollaborationInvitationResponses,
    SendCollaborationInvitationErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      SendCollaborationInvitationResponses,
      SendCollaborationInvitationErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/collaboration/invite",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Remove a collaborator from the business
   *
   * Removes a collaborator from the specified business.
   */
  public static removeCollaboratorFromBusiness<
    ThrowOnError extends boolean = false,
  >(
    options: Options<RemoveCollaboratorFromBusinessData, ThrowOnError>,
  ): RequestResult<
    RemoveCollaboratorFromBusinessResponses,
    unknown,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      RemoveCollaboratorFromBusinessResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/collaborator/remove",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Count collaborators by business ID
   *
   * Retrieves the total number of collaborators for a given business.
   */
  public static countCollaboratorsByBusinessId<
    ThrowOnError extends boolean = false,
  >(
    options: Options<CountCollaboratorsByBusinessIdData, ThrowOnError>,
  ): RequestResult<
    CountCollaboratorsByBusinessIdResponses,
    unknown,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      CountCollaboratorsByBusinessIdResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/business/{businessId}/collaborator/count", ...options });
  }

  /**
   * Update business images
   *
   * Updates the logo and/or banner images of a business
   */
  public static updateBusinessImages<ThrowOnError extends boolean = false>(
    options: Options<UpdateBusinessImagesData, ThrowOnError>,
  ): RequestResult<
    UpdateBusinessImagesResponses,
    UpdateBusinessImagesErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UpdateBusinessImagesResponses,
      UpdateBusinessImagesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/images",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get all business types
   *
   * Retrieves a list of all available business types
   */
  public static getAllBusinessTypes<ThrowOnError extends boolean = false>(
    options?: Options<GetAllBusinessTypesData, ThrowOnError>,
  ): RequestResult<GetAllBusinessTypesResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      GetAllBusinessTypesResponses,
      unknown,
      ThrowOnError
    >({ url: "/public/business/types", ...options });
  }

  /**
   * Get all businesses
   *
   * Retrieves a paginated list of published businesses with optional filters.
   */
  public static getAllBusinesses<ThrowOnError extends boolean = false>(
    options: Options<GetAllBusinessesData, ThrowOnError>,
  ): RequestResult<GetAllBusinessesResponses, unknown, ThrowOnError> {
    return (options.client ?? client).get<
      GetAllBusinessesResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/public/business",
      ...options,
    });
  }

  /**
   * Get businesses by IDs
   *
   * Retrieves a list of businesses matching the provided IDs. No pagination.
   */
  public static getBusinessesByIds<ThrowOnError extends boolean = false>(
    options: Options<GetBusinessesByIdsData, ThrowOnError>,
  ): RequestResult<GetBusinessesByIdsResponses, unknown, ThrowOnError> {
    return (options.client ?? client).post<
      GetBusinessesByIdsResponses,
      unknown,
      ThrowOnError
    >({
      url: "/public/business/by-ids",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get All Business for the Current User
   *
   * Retrieves a list of all business available to the authenticated user. Authentication is managed using a token without scopes.
   */
  public static getMyBusinesses<ThrowOnError extends boolean = false>(
    options?: Options<GetMyBusinessesData, ThrowOnError>,
  ): RequestResult<GetMyBusinessesResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      GetMyBusinessesResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business",
      ...options,
    });
  }

  /**
   * Create a new business
   *
   * Creates a new business
   */
  public static createMyBusiness<ThrowOnError extends boolean = false>(
    options: Options<CreateMyBusinessData, ThrowOnError>,
  ): RequestResult<
    CreateMyBusinessResponses,
    CreateMyBusinessErrors,
    ThrowOnError
  > {
    return (options.client ?? client).post<
      CreateMyBusinessResponses,
      CreateMyBusinessErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Update my business
   *
   * Updates an existing business by its ID.
   */
  public static updateMyBusinesses<ThrowOnError extends boolean = false>(
    options: Options<UpdateMyBusinessesData, ThrowOnError>,
  ): RequestResult<
    UpdateMyBusinessesResponses,
    UpdateMyBusinessesErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UpdateMyBusinessesResponses,
      UpdateMyBusinessesErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Publish a business
   *
   * Publishes a business, making it visible to the public.
   */
  public static publishMyBusiness<ThrowOnError extends boolean = false>(
    options: Options<PublishMyBusinessData, ThrowOnError>,
  ): RequestResult<
    PublishMyBusinessResponses,
    PublishMyBusinessErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      PublishMyBusinessResponses,
      PublishMyBusinessErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/publish",
      ...options,
    });
  }

  /**
   * Unpublish a business
   *
   * Unpublishes a business, hiding it from the public.
   */
  public static unpublishMyBusiness<ThrowOnError extends boolean = false>(
    options: Options<UnpublishMyBusinessData, ThrowOnError>,
  ): RequestResult<
    UnpublishMyBusinessResponses,
    UnpublishMyBusinessErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UnpublishMyBusinessResponses,
      UnpublishMyBusinessErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/{businessId}/unpublish",
      ...options,
    });
  }

  /**
   * Retrieve business count
   *
   * Returns the total number of businesses associated with the authenticated user's account
   */
  public static getMyBusinessCount<ThrowOnError extends boolean = false>(
    options?: Options<GetMyBusinessCountData, ThrowOnError>,
  ): RequestResult<
    GetMyBusinessCountResponses,
    GetMyBusinessCountErrors,
    ThrowOnError
  > {
    return (options?.client ?? client).get<
      GetMyBusinessCountResponses,
      GetMyBusinessCountErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business/count",
      ...options,
    });
  }

  /**
   * Get all user permissions by context
   *
   * Retrieves all permissions for a given user within a specific business.
   * Permissions are grouped by CONTEXT (e.g. PRODUCT, ADVERT, ORDER, SONDAGE).
   * Each context defines the allowed actions: create, read, update, delete, publish, etc.
   * This endpoint provides a global and extensible permission view.
   *
   */
  public static getUserPermissions<ThrowOnError extends boolean = false>(
    options: Options<GetUserPermissionsData, ThrowOnError>,
  ): RequestResult<
    GetUserPermissionsResponses,
    GetUserPermissionsErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetUserPermissionsResponses,
      GetUserPermissionsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}/user/{username}/permissions",
      ...options,
    });
  }

  /**
   * Get business by ID
   *
   * Retrieves a specific business by its ID.
   */
  public static getBusinessById<ThrowOnError extends boolean = false>(
    options: Options<GetBusinessByIdData, ThrowOnError>,
  ): RequestResult<
    GetBusinessByIdResponses,
    GetBusinessByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).get<
      GetBusinessByIdResponses,
      GetBusinessByIdErrors,
      ThrowOnError
    >({ url: "/public/business/{id}", ...options });
  }

  /**
   * Delete business by ID
   *
   * Deletes an existing business by its ID.
   */
  public static deleteBusinessById<ThrowOnError extends boolean = false>(
    options: Options<DeleteBusinessByIdData, ThrowOnError>,
  ): RequestResult<
    DeleteBusinessByIdResponses,
    DeleteBusinessByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).delete<
      DeleteBusinessByIdResponses,
      DeleteBusinessByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business/{businessId}",
      ...options,
    });
  }
}

export class BusinessZone {
  /**
   * Get all business zone
   *
   * Retrieves a list of all available business zone.
   */
  public static getAllBusinessesZone<ThrowOnError extends boolean = false>(
    options?: Options<GetAllBusinessesZoneData, ThrowOnError>,
  ): RequestResult<GetAllBusinessesZoneResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      GetAllBusinessesZoneResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business-zone",
      ...options,
    });
  }

  /**
   * Get my business zone
   *
   * Get my business zone
   */
  public static getMyBusinessZone<ThrowOnError extends boolean = false>(
    options?: Options<GetMyBusinessZoneData, ThrowOnError>,
  ): RequestResult<GetMyBusinessZoneResponses, unknown, ThrowOnError> {
    return (options?.client ?? client).get<
      GetMyBusinessZoneResponses,
      unknown,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business-zone",
      ...options,
    });
  }

  /**
   * Update my business zone
   *
   * Update my business zone
   */
  public static updateMyBusinessZone<ThrowOnError extends boolean = false>(
    options: Options<UpdateMyBusinessZoneData, ThrowOnError>,
  ): RequestResult<
    UpdateMyBusinessZoneResponses,
    UpdateMyBusinessZoneErrors,
    ThrowOnError
  > {
    return (options.client ?? client).put<
      UpdateMyBusinessZoneResponses,
      UpdateMyBusinessZoneErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/business-zone",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete business zone by ID
   *
   * Deletes an existing business zone by its ID.
   */
  public static deleteBusinessZoneById<ThrowOnError extends boolean = false>(
    options: Options<DeleteBusinessZoneByIdData, ThrowOnError>,
  ): RequestResult<
    DeleteBusinessZoneByIdResponses,
    DeleteBusinessZoneByIdErrors,
    ThrowOnError
  > {
    return (options.client ?? client).delete<
      DeleteBusinessZoneByIdResponses,
      DeleteBusinessZoneByIdErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/business-zone/{businessZoneId}",
      ...options,
    });
  }
}

export class Collaboration {
  /**
   * Get all my collaborations
   *
   * Retrieves a list of all collaborations for the authenticated user's account.
   */
  public static getMyCollaborations<ThrowOnError extends boolean = false>(
    options?: Options<GetMyCollaborationsData, ThrowOnError>,
  ): RequestResult<
    GetMyCollaborationsResponses,
    GetMyCollaborationsErrors,
    ThrowOnError
  > {
    return (options?.client ?? client).get<
      GetMyCollaborationsResponses,
      GetMyCollaborationsErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/my/collaborations",
      ...options,
    });
  }
}
