// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8181/api" | (string & {});
};

export const BusinessSortFieldDto = {
  CREATED_AT: "CREATED_AT",
  NAME: "NAME",
} as const;

export type BusinessSortFieldDto =
  (typeof BusinessSortFieldDto)[keyof typeof BusinessSortFieldDto];

export const SortDirectionDto = { ASC: "ASC", DESC: "DESC" } as const;

export type SortDirectionDto =
  (typeof SortDirectionDto)[keyof typeof SortDirectionDto];

export type BusinessPageableResponseDto = {
  content?: Array<BusinessDto>;
  page?: PageableResponsePageDto;
};

export type PageableResponsePageDto = {
  /**
   * Number of items per page
   */
  size?: number;
  /**
   * Current page number (zero-based)
   */
  number?: number;
  /**
   * Total number of items across all pages
   */
  totalElements?: number;
  /**
   * Total number of pages
   */
  totalPages?: number;
};

export type CreateResponseDto = {
  id?: string;
};

export type InvitationDto = {
  id?: string;
  businessId?: string;
  businessName?: string;
  invitedBy?: string;
  invitedUsername?: string;
  roles?: Array<CollaboratorRoleDto>;
  status?: InvitationStatusDto;
  createdAt?: string;
  respondedAt?: string;
  rejectionReason?: string;
};

export const InvitationStatusDto = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
} as const;

export type InvitationStatusDto =
  (typeof InvitationStatusDto)[keyof typeof InvitationStatusDto];

export type RejectInvitationRequestDto = {
  reason?: string;
};

export type CollaborationDto = {
  businessId?: string;
  businessName?: string;
  businessDescription?: string;
  invitedBy?: string;
  invitedUsername?: string;
  permissions?: Array<CollaboratorRoleDto>;
  isActive?: boolean;
  createdAt?: string;
};

export type BusinessIdsRequestDto = {
  businessIds: Array<string>;
};

export type UpdateBusinessImagesDto = {
  logo?: string;
  banner?: string;
};

export type CountResponseDto = {
  value?: number;
};

/**
 * All permissions for a user grouped by context.
 */
export type UserPermissionsDto = {
  /**
   * List of permission contexts with allowed actions.
   */
  permissions?: Array<ContextPermissionDto>;
  /**
   * Roles that grant these permissions.
   */
  effectiveRoles?: Array<RoleTypeDto>;
};

export type ContextPermissionDto = {
  context: PermissionContextDto;
  /**
   * User is allowed to create entities for this context.
   */
  canCreate?: boolean;
  /**
   * User can retrieve/view entities for this context.
   */
  canRead?: boolean;
  /**
   * User can modify existing entities for this context.
   */
  canUpdate?: boolean;
  /**
   * User can delete entities for this context.
   */
  canDelete?: boolean;
  /**
   * User can publish/unpublish entities for this context.
   */
  canPublish?: boolean;
};

/**
 * The context to which permissions apply.
 */
export const PermissionContextDto = {
  PRODUCT: "PRODUCT",
  ADVERT: "ADVERT",
  SONDAGE: "SONDAGE",
  ORDER: "ORDER",
} as const;

/**
 * The context to which permissions apply.
 */
export type PermissionContextDto =
  (typeof PermissionContextDto)[keyof typeof PermissionContextDto];

export type CreateBusinessZoneDto = {
  /**
   * Name of the business zone
   */
  name: string;
  /**
   * Description of the business zone
   */
  description?: string;
};

export type UpdateBusinessZoneDto = {
  /**
   * Name of the business zone
   */
  name?: string;
  /**
   * Description of the business zone
   */
  description?: string;
};

export type BusinessZoneDto = {
  /**
   * Unique identifier of the business zone
   */
  id: string;
  /**
   * Name of the business zone
   */
  name: string;
  /**
   * Description of the business zone
   */
  description?: string;
  /**
   * Timestamp when the business zone was created
   */
  createdAt?: string;
  /**
   * Timestamp when the business zone was last updated
   */
  updatedAt?: string;
  /**
   * Whether the business zone is active
   */
  active?: boolean;
};

export type BusinessZoneIdDto = {
  id: string;
};

export type BusinessPhoneDto = {
  /**
   * Context/usage of the phone number (e.g. whatsapp, main, fax)
   */
  usage: string;
  number: PhoneNumberDto;
};

export type CreateBusinessDto = {
  /**
   * Name of the business
   */
  name: string;
  /**
   * Description of the business
   */
  description?: string;
  /**
   * Physical address of the business
   */
  address: string;
  /**
   * List of phone numbers with their context
   */
  phones: Array<BusinessPhoneDto>;
  /**
   * Email address of the business
   */
  email: string;
  type: string;
  /**
   * Whether the business is active
   */
  active?: boolean;
  /**
   * Map of image names to their url
   */
  images?: {
    [key: string]: string;
  };
};

export type UpdateBusinessDto = {
  /**
   * Name of the business
   */
  name?: string;
  /**
   * Description of the business
   */
  description?: string;
  /**
   * Physical address of the business
   */
  address?: string;
  /**
   * Map of phone numbers grouped by context (e.g., 'work', 'personal', 'emergency')
   */
  phones?: {
    [key: string]: Array<PhoneNumberDto>;
  };
  /**
   * Email address of the business
   */
  email?: string;
  type?: string;
  /**
   * Whether the business is active
   */
  active?: boolean;
  /**
   * Map of image names to their url
   */
  images?: {
    [key: string]: string;
  };
};

export type BusinessTypeDto = {
  /**
   * Unique identifier of the business type
   */
  id?: string;
  /**
   * English name of the business type
   */
  nameEn?: string;
  /**
   * English description of the business type
   */
  descriptionEn?: string;
  /**
   * French name of the business type
   */
  nameFr?: string;
  /**
   * French description of the business type
   */
  descriptionFr?: string;
};

export type BusinessDto = {
  /**
   * Unique identifier of the business
   */
  id: string;
  /**
   * Name of the business
   */
  name: string;
  /**
   * Description of the business
   */
  description?: string;
  /**
   * Physical address of the business
   */
  address: string;
  /**
   * Map of phone numbers grouped by context (e.g., 'work', 'personal', 'emergency')
   */
  phones?: {
    [key: string]: Array<PhoneNumberDto>;
  };
  /**
   * Email address of the business
   */
  email: string;
  type: BusinessTypeDto;
  /**
   * Whether the business is active
   */
  active: boolean;
  images?: {
    [key: string]: string;
  };
  /**
   * Timestamp when the business was created
   */
  createdAt?: string;
  /**
   * Timestamp when the business was last updated
   */
  updatedAt?: string;
  owner?: string;
};

export type BusinessIdDto = {
  /**
   * Unique identifier of the created business
   */
  id: string;
};

export type PhoneNumberDto = {
  number?: string;
  countryCode?: string;
};

export type ProductManagementPermissionDto = {
  /**
   * Global permission flag. True if the user has any product management rights.
   */
  canManageProducts?: boolean;
  permissions?: ProductPermissionDto;
  /**
   * List of roles that grant these permissions
   */
  effectiveRoles?: Array<RoleTypeDto>;
};

export type ProductPermissionDto = {
  /**
   * Permission to create new products.
   */
  canCreate?: boolean;
  /**
   * Permission to view/retrieve products.
   */
  canRead?: boolean;
  /**
   * Permission to edit existing products.
   */
  canUpdate?: boolean;
  /**
   * Permission to delete products.
   */
  canDelete?: boolean;
  /**
   * Permission to change the published status of products.
   */
  canPublish?: boolean;
};

/**
 * The role that grants permissions.
 */
export const RoleTypeDto = {
  OWNER: "OWNER",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  ORDER_MANAGER: "ORDER_MANAGER",
  ADVERT_MANAGER: "ADVERT_MANAGER",
  SONDAGE_MANAGER: "SONDAGE_MANAGER",
  DELIVERY_AGENT: "DELIVERY_AGENT",
} as const;

/**
 * The role that grants permissions.
 */
export type RoleTypeDto = (typeof RoleTypeDto)[keyof typeof RoleTypeDto];

export type CollaboratorDto = {
  /**
   * The username of the collaborator.
   */
  username?: string;
  /**
   * The roles of the collaborator in the business.
   */
  roles?: Array<CollaboratorRoleDto>;
  /**
   * The date and time when the collaborator was added to the business.
   */
  addedAt?: string;
};

export type InviteCollaboratorRequestDto = {
  /**
   * Username of the existing user to be added as a collaborator
   */
  username: string;
  roles: Array<InviteCollaboratorRoleDto>;
};

export type RemoveCollaboratorRequestDto = {
  /**
   * Username of the collaborator to remove from the business
   */
  username: string;
  /**
   * Optional reason for removing the collaborator
   */
  reason?: string;
};

/**
 * The role that can be assigned to a collaborator.
 */
export const CollaboratorRoleDto = {
  OWNER: "OWNER",
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  ORDER_MANAGER: "ORDER_MANAGER",
  ADVERT_MANAGER: "ADVERT_MANAGER",
  SONDAGE_MANAGER: "SONDAGE_MANAGER",
  DELIVERY_AGENT: "DELIVERY_AGENT",
} as const;

/**
 * The role that can be assigned to a collaborator.
 */
export type CollaboratorRoleDto =
  (typeof CollaboratorRoleDto)[keyof typeof CollaboratorRoleDto];

/**
 * The role that can be assigned to a collaborator.
 */
export const InviteCollaboratorRoleDto = {
  PRODUCT_MANAGER: "PRODUCT_MANAGER",
  ORDER_MANAGER: "ORDER_MANAGER",
  ADVERT_MANAGER: "ADVERT_MANAGER",
  SONDAGE_MANAGER: "SONDAGE_MANAGER",
  DELIVERY_AGENT: "DELIVERY_AGENT",
} as const;

/**
 * The role that can be assigned to a collaborator.
 */
export type InviteCollaboratorRoleDto =
  (typeof InviteCollaboratorRoleDto)[keyof typeof InviteCollaboratorRoleDto];

export type GetMyInvitationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/my/invitations";
};

export type GetMyInvitationsResponses = {
  /**
   * A list of invitations for the user.
   */
  200: Array<InvitationDto>;
};

export type GetMyInvitationsResponse =
  GetMyInvitationsResponses[keyof GetMyInvitationsResponses];

export type AcceptInvitationData = {
  body?: never;
  path: {
    invitationId: string;
  };
  query?: never;
  url: "/my/invitations/{invitationId}/accept";
};

export type AcceptInvitationErrors = {
  /**
   * Invitation not found.
   */
  404: unknown;
};

export type AcceptInvitationResponses = {
  /**
   * Invitation accepted successfully.
   */
  200: unknown;
};

export type RejectInvitationData = {
  body?: RejectInvitationRequestDto;
  path: {
    invitationId: string;
  };
  query?: never;
  url: "/my/invitations/{invitationId}/reject";
};

export type RejectInvitationErrors = {
  /**
   * Invitation not found.
   */
  404: unknown;
};

export type RejectInvitationResponses = {
  /**
   * Invitation rejected successfully.
   */
  200: unknown;
};

export type GetBusinessInvitationsData = {
  body?: never;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/invitations";
};

export type GetBusinessInvitationsResponses = {
  /**
   * A list of invitations for the business.
   */
  200: Array<InvitationDto>;
};

export type GetBusinessInvitationsResponse =
  GetBusinessInvitationsResponses[keyof GetBusinessInvitationsResponses];

export type CancelInvitationData = {
  body?: never;
  path: {
    invitationId: string;
  };
  query?: never;
  url: "/my/invitations/{invitationId}/cancel";
};

export type CancelInvitationErrors = {
  /**
   * Only the owner can cancel invitations.
   */
  403: unknown;
  /**
   * Business or invitation not found.
   */
  404: unknown;
};

export type CancelInvitationResponses = {
  /**
   * Invitation cancelled successfully.
   */
  204: void;
};

export type CancelInvitationResponse =
  CancelInvitationResponses[keyof CancelInvitationResponses];

export type GetBusinessCollaboratorsData = {
  body?: never;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/collaborator";
};

export type GetBusinessCollaboratorsResponses = {
  /**
   * A list of collaborators for the business.
   */
  200: Array<CollaboratorDto>;
};

export type GetBusinessCollaboratorsResponse =
  GetBusinessCollaboratorsResponses[keyof GetBusinessCollaboratorsResponses];

export type SendCollaborationInvitationData = {
  body: InviteCollaboratorRequestDto;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/collaboration/invite";
};

export type SendCollaborationInvitationErrors = {
  /**
   * You are not the owner of this business
   */
  403: unknown;
  /**
   * Business or invitee not found
   */
  404: unknown;
  /**
   * Pending invitation already exists or user is already a collaborator
   */
  409: unknown;
};

export type SendCollaborationInvitationResponses = {
  /**
   * Invitation sent successfully
   */
  201: CreateResponseDto;
};

export type SendCollaborationInvitationResponse =
  SendCollaborationInvitationResponses[keyof SendCollaborationInvitationResponses];

export type RemoveCollaboratorFromBusinessData = {
  body: RemoveCollaboratorRequestDto;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/collaborator/remove";
};

export type RemoveCollaboratorFromBusinessResponses = {
  /**
   * Collaborator removed successfully
   */
  200: unknown;
};

export type CountCollaboratorsByBusinessIdData = {
  body?: never;
  path: {
    businessId: string;
  };
  query?: never;
  url: "/public/business/{businessId}/collaborator/count";
};

export type CountCollaboratorsByBusinessIdResponses = {
  /**
   * Total number of collaborators
   */
  200: CountResponseDto;
};

export type CountCollaboratorsByBusinessIdResponse =
  CountCollaboratorsByBusinessIdResponses[keyof CountCollaboratorsByBusinessIdResponses];

export type UpdateBusinessImagesData = {
  body: UpdateBusinessImagesDto;
  path: {
    /**
     * The ID of the business to update images
     */
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/images";
};

export type UpdateBusinessImagesErrors = {
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
  /**
   * Business not found
   */
  404: unknown;
};

export type UpdateBusinessImagesResponses = {
  /**
   * Business images updated successfully
   */
  204: BusinessDto;
};

export type UpdateBusinessImagesResponse =
  UpdateBusinessImagesResponses[keyof UpdateBusinessImagesResponses];

export type GetAllBusinessTypesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/public/business/types";
};

export type GetAllBusinessTypesResponses = {
  /**
   * List of business types retrieved successfully
   */
  200: Array<BusinessTypeDto>;
};

export type GetAllBusinessTypesResponse =
  GetAllBusinessTypesResponses[keyof GetAllBusinessTypesResponses];

export type GetAllBusinessesZoneData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/business-zone";
};

export type GetAllBusinessesZoneResponses = {
  /**
   * List of business zone retrieved successfully
   */
  200: Array<BusinessZoneDto>;
};

export type GetAllBusinessesZoneResponse =
  GetAllBusinessesZoneResponses[keyof GetAllBusinessesZoneResponses];

export type GetMyBusinessZoneData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/my/business-zone";
};

export type GetMyBusinessZoneResponses = {
  /**
   * business zone found
   */
  200: BusinessZoneDto;
};

export type GetMyBusinessZoneResponse =
  GetMyBusinessZoneResponses[keyof GetMyBusinessZoneResponses];

export type UpdateMyBusinessZoneData = {
  body: UpdateBusinessZoneDto;
  path?: never;
  query?: never;
  url: "/my/business-zone";
};

export type UpdateMyBusinessZoneErrors = {
  /**
   * Bad request - Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
};

export type UpdateMyBusinessZoneResponses = {
  /**
   * business zone updated successfully
   */
  200: BusinessZoneDto;
};

export type UpdateMyBusinessZoneResponse =
  UpdateMyBusinessZoneResponses[keyof UpdateMyBusinessZoneResponses];

export type DeleteBusinessZoneByIdData = {
  body?: never;
  path: {
    /**
     * The ID of the business zone to delete
     */
    businessZoneId: string;
  };
  query?: never;
  url: "/business-zone/{businessZoneId}";
};

export type DeleteBusinessZoneByIdErrors = {
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
  /**
   * business zone not found
   */
  404: unknown;
};

export type DeleteBusinessZoneByIdResponses = {
  /**
   * business zone successfully deleted
   */
  204: void;
};

export type DeleteBusinessZoneByIdResponse =
  DeleteBusinessZoneByIdResponses[keyof DeleteBusinessZoneByIdResponses];

export type GetAllBusinessesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Page number (zero-based)
     */
    page: number;
    /**
     * Number of items per page
     */
    size?: number;
    field?: BusinessSortFieldDto;
    direction?: SortDirectionDto;
    /**
     * Filter by business name (case-insensitive)
     */
    name?: string;
    /**
     * Filter by business type ID
     */
    type?: string;
  };
  url: "/public/business";
};

export type GetAllBusinessesResponses = {
  /**
   * Paginated list of businesses retrieved successfully
   */
  200: BusinessPageableResponseDto;
};

export type GetAllBusinessesResponse =
  GetAllBusinessesResponses[keyof GetAllBusinessesResponses];

export type GetBusinessesByIdsData = {
  body: BusinessIdsRequestDto;
  path?: never;
  query?: {
    /**
     * Specifies which business fields should be extracted and returned in the response.
     */
    extractCode?: string;
  };
  url: "/public/business/by-ids";
};

export type GetBusinessesByIdsResponses = {
  /**
   * List of businesses retrieved successfully
   */
  200: Array<BusinessDto>;
};

export type GetBusinessesByIdsResponse =
  GetBusinessesByIdsResponses[keyof GetBusinessesByIdsResponses];

export type GetMyBusinessesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/my/business";
};

export type GetMyBusinessesResponses = {
  /**
   * Successfully retrieved the list of business
   */
  200: Array<BusinessDto>;
};

export type GetMyBusinessesResponse =
  GetMyBusinessesResponses[keyof GetMyBusinessesResponses];

export type CreateMyBusinessData = {
  body: CreateBusinessDto;
  path?: never;
  query?: never;
  url: "/my/business";
};

export type CreateMyBusinessErrors = {
  /**
   * Bad request - Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
};

export type CreateMyBusinessResponses = {
  /**
   * business created successfully
   */
  201: BusinessIdDto;
};

export type CreateMyBusinessResponse =
  CreateMyBusinessResponses[keyof CreateMyBusinessResponses];

export type UpdateMyBusinessesData = {
  body: UpdateBusinessDto;
  path: {
    /**
     * The ID of my business to update
     */
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}";
};

export type UpdateMyBusinessesErrors = {
  /**
   * Bad request - Invalid input data
   */
  400: unknown;
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
  /**
   * business not found
   */
  404: unknown;
};

export type UpdateMyBusinessesResponses = {
  /**
   * business updated successfully
   */
  200: BusinessDto;
};

export type UpdateMyBusinessesResponse =
  UpdateMyBusinessesResponses[keyof UpdateMyBusinessesResponses];

export type PublishMyBusinessData = {
  body?: never;
  path: {
    /**
     * The ID of the business to publish
     */
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/publish";
};

export type PublishMyBusinessErrors = {
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
  /**
   * Business not found
   */
  404: unknown;
};

export type PublishMyBusinessResponses = {
  /**
   * Business published successfully
   */
  200: unknown;
};

export type UnpublishMyBusinessData = {
  body?: never;
  path: {
    /**
     * The ID of the business to unpublish
     */
    businessId: string;
  };
  query?: never;
  url: "/my/business/{businessId}/unpublish";
};

export type UnpublishMyBusinessErrors = {
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
  /**
   * Business not found
   */
  404: unknown;
};

export type UnpublishMyBusinessResponses = {
  /**
   * Business unpublished successfully
   */
  200: unknown;
};

export type GetMyBusinessCountData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/my/business/count";
};

export type GetMyBusinessCountErrors = {
  /**
   * Bad request - The request contains invalid parameters or malformed data
   */
  400: unknown;
  /**
   * Unauthorized - Authentication token is missing, expired, or invalid
   */
  401: unknown;
};

export type GetMyBusinessCountResponses = {
  /**
   * Business count retrieved successfully
   */
  200: CountResponseDto;
};

export type GetMyBusinessCountResponse =
  GetMyBusinessCountResponses[keyof GetMyBusinessCountResponses];

export type GetUserPermissionsData = {
  body?: never;
  path: {
    /**
     * The unique identifier of the business.
     */
    businessId: string;
    /**
     * The username of the user to retrieve permissions for.
     */
    username: string;
  };
  query?: never;
  url: "/business/{businessId}/user/{username}/permissions";
};

export type GetUserPermissionsErrors = {
  /**
   * Invalid input data.
   */
  400: unknown;
  /**
   * Authentication required.
   */
  401: unknown;
  /**
   * Forbidden.
   */
  403: unknown;
  /**
   * User or business not found.
   */
  404: unknown;
};

export type GetUserPermissionsResponses = {
  /**
   * Successfully retrieved user permissions.
   */
  200: UserPermissionsDto;
};

export type GetUserPermissionsResponse =
  GetUserPermissionsResponses[keyof GetUserPermissionsResponses];

export type GetBusinessByIdData = {
  body?: never;
  path: {
    /**
     * The ID of the business to retrieve
     */
    id: string;
  };
  query?: never;
  url: "/public/business/{id}";
};

export type GetBusinessByIdErrors = {
  /**
   * business not found
   */
  404: unknown;
};

export type GetBusinessByIdResponses = {
  /**
   * business found
   */
  200: BusinessDto;
};

export type GetBusinessByIdResponse =
  GetBusinessByIdResponses[keyof GetBusinessByIdResponses];

export type DeleteBusinessByIdData = {
  body?: never;
  path: {
    /**
     * The ID of the business to delete
     */
    businessId: string;
  };
  query?: never;
  url: "/business/{businessId}";
};

export type DeleteBusinessByIdErrors = {
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to perform this operation
   */
  403: unknown;
  /**
   * business not found
   */
  404: unknown;
};

export type DeleteBusinessByIdResponses = {
  /**
   * business successfully deleted
   */
  204: void;
};

export type DeleteBusinessByIdResponse =
  DeleteBusinessByIdResponses[keyof DeleteBusinessByIdResponses];

export type GetMyCollaborationsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/my/collaborations";
};

export type GetMyCollaborationsErrors = {
  /**
   * Unauthorized - Authentication token is missing or invalid
   */
  401: unknown;
  /**
   * Forbidden - The user does not have permission to access this resource
   */
  403: unknown;
  /**
   * Business not found
   */
  404: unknown;
};

export type GetMyCollaborationsResponses = {
  /**
   * A list of collaborations for the user.
   */
  200: Array<CollaborationDto>;
};

export type GetMyCollaborationsResponse =
  GetMyCollaborationsResponses[keyof GetMyCollaborationsResponses];
